CREATE TABLE IF NOT EXISTS MPA
(
	RATING_ID	INTEGER PRIMARY KEY AUTO_INCREMENT,
	RATING		VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS FILMS
(
	FILM_ID 	 	INTEGER PRIMARY KEY AUTO_INCREMENT,
	NAME 		 	VARCHAR(255) NOT NULL,
	DESCRIPTION  	VARCHAR(200) NOT NULL,
	RELEASE_DATE 	DATE,
	DURATION 	 	INTEGER,
	RATING_ID 	 	INTEGER REFERENCES MPA(RATING_ID)
);

CREATE TABLE IF NOT EXISTS GENRE
(
	GENRE_ID	INTEGER PRIMARY KEY AUTO_INCREMENT,
	GENRE		VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
	FILM_ID		INTEGER REFERENCES FILMS(FILM_ID),
	GENRE_ID 	INTEGER REFERENCES GENRE(GENRE_ID),
	UNIQUE 		(FILM_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS USERS
(
	USER_ID 	 	INTEGER PRIMARY KEY AUTO_INCREMENT,
	EMAIL 		 	VARCHAR(255) NOT NULL,
	LOGIN  			VARCHAR(255) NOT NULL,
	USER_NAME 		VARCHAR(255) NOT NULL,
	BIRTHDAY		DATE
);

CREATE TABLE IF NOT EXISTS FILM_LIKES
(
	USER_ID		INTEGER REFERENCES USERS(USER_ID),
	FILM_ID		INTEGER REFERENCES FILMS(FILM_ID),
	UNIQUE(USER_ID, FILM_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP
(
	USER_ID 	INTEGER REFERENCES USERS(USER_ID),
	FRIEND_ID	INTEGER REFERENCES USERS(USER_ID),
	STATUS 		BOOLEAN
);